include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

linter:
  rules:
    always_use_package_imports: true
    directives_ordering: true

dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/flutter_all.yaml
