name: basso_hoogerheide
version: 1.0.0+1

environment:
  flutter: ">=3.3.3 <4.0.0"
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_mask: ^2.0.1
  infinite_listview: ^1.1.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  file_picker: ^5.0.1
  flutter_riverpod: ^1.0.4
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  flutter_local_notifications: ^12.0.0
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
