name: basso_hoogerheide
version: 1.1.1+25

environment:
  flutter: ^3.3.10
  sdk: ^2.18.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  easy_mask: ^2.0.1
  infinite_listview: ^1.1.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  file_picker: ^5.2.5
  flutter_riverpod: ^2.1.3
  flutter_secure_storage: ^8.0.0
  http: ^0.13.5
  awesome_notifications: ^0.7.4+1
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  url_launcher: ^6.1.9
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icons/logo.svg

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
